"""
AI/ML Crossword Solver & Puzzle Factory
Generates and verifies 15x15 crossword configurations with 100% exact letter intersections.
"""
import random
import copy
from typing import List, Dict, Tuple, Optional
from backend.puzzle_validator import validate_crossword_puzzle, print_grid

# Comprehensive AI/ML lexicon with definitions and categories
VOCABULARY = {
    # 3-letter
    "RAG": ("Retrieval Augmented Generation", "Technique combining external semantic search retrieval with large language models.", "Generative AI"),
    "CNN": ("CNN", "Convolutional Neural Network architecture specialized for 2D/3D spatial grid patterns.", "Computer Vision"),
    "RNN": ("RNN", "Recurrent Neural Network maintaining a cyclical hidden state for sequential data.", "Deep Learning"),
    "GAN": ("GAN", "Generative Adversarial Network pitting a generator against a discriminator network.", "Generative AI"),
    "VAE": ("VAE", "Variational Autoencoder learning a continuous structured latent space with KL divergence.", "Generative AI"),
    "SGD": ("SGD", "Stochastic Gradient Descent updating weights on random mini-batches of training data.", "Optimization"),
    "LLM": ("LLM", "Large Language Model trained on massive web-scale corpora via autoregressive token prediction.", "Generative AI"),
    "PCA": ("PCA", "Principal Component Analysis reducing dimensionality by projecting onto orthogonal axes of maximum variance.", "Machine Learning"),
    "KNN": ("K-NN", "K-Nearest Neighbors non-parametric classification algorithm voting by Euclidean or cosine distance.", "Machine Learning"),
    "SVM": ("SVM", "Support Vector Machine finding the optimal separating hyperplane with maximum margin.", "Machine Learning"),
    "ROC": ("ROC", "Receiver Operating Characteristic curve plotting True Positive Rate versus False Positive Rate.", "Evaluation"),
    "AUC": ("AUC", "Area Under the ROC Curve measuring aggregate classification performance across all thresholds.", "Evaluation"),
    
    # 4-letter
    "ADAM": ("Adam", "Adaptive Moment Estimation optimizer computing individual adaptive learning rates from 1st and 2nd moments.", "Optimization"),
    "BERT": ("BERT", "Bidirectional Encoder Representations from Transformers pre-trained with masked language modeling.", "NLP"),
    "BIAS": ("Bias", "Systematic deviation error resulting from erroneous simplifying assumptions in the learning algorithm.", "Machine Learning"),
    "LOSS": ("Loss", "Objective scalar measuring prediction discrepancy against ground truth targets.", "Machine Learning"),
    "RELU": ("ReLU", "Rectified Linear Unit activation function computing f(x) = max(0, x).", "Deep Learning"),
    "NODE": ("Node", "Individual computational vertex or artificial neuron in a neural network graph.", "Deep Learning"),
    "TREE": ("Tree", "Hierarchical decision graph splitting feature spaces recursively at internal nodes.", "Machine Learning"),
    "COST": ("Cost", "Cumulative loss penalty calculated across the entire dataset or batch.", "Machine Learning"),
    
    # 5-letter
    "EPOCH": ("Epoch", "One full forward and backward pass of the entire training dataset through the network.", "Deep Learning"),
    "LOGIT": ("Logit", "Unnormalized raw scalar score generated by the final linear layer before softmax.", "Deep Learning"),
    "BATCH": ("Batch", "Subset of training samples evaluated simultaneously in one forward-backward pass.", "Deep Learning"),
    "LAYER": ("Layer", "Collection of parallel artificial neurons processing intermediate representation tensors.", "Deep Learning"),
    "TRAIN": ("Train", "Phase where model weights are iteratively updated using optimization algorithms.", "Machine Learning"),
    
    # 6-letter
    "TENSOR": ("Tensor", "Multidimensional generalization of scalars, vectors, and matrices to arbitrary rank.", "Mathematics"),
    "PROMPT": ("Prompt", "Natural language instructions and context fed into a generative foundation model.", "Generative AI"),
    "LATENT": ("Latent", "Hidden, unobserved compressed manifold space encoding intrinsic data representations.", "Deep Learning"),
    "WEIGHT": ("Weight", "Learnable multiplicative parameter in a neural network connection.", "Deep Learning"),
    "MATRIX": ("Matrix", "Two-dimensional rectangular numerical array representing linear operators.", "Mathematics"),
    "VECTOR": ("Vector", "One-dimensional array with magnitude and direction in a vector space.", "Mathematics"),
    "RESNET": ("ResNet", "Deep convolutional architecture using residual skip connections to bypass layers.", "Computer Vision"),
    "RECALL": ("Recall", "Ratio of true positive detections over total actual positive ground truth instances.", "Evaluation"),
    
    # 7-letter
    "DROPOUT": ("Dropout", "Stochastic regularization deactivating hidden units with probability p during training.", "Deep Learning"),
    "SIGMOID": ("Sigmoid", "S-shaped activation function mapping real numbers into probability interval (0, 1).", "Deep Learning"),
    "SOFTMAX": ("Softmax", "Function converting raw logit vectors into normalized probability distributions.", "Deep Learning"),
    "ENCODER": ("Encoder", "Sub-network compressing high-dimensional input sequences into latent context vectors.", "Deep Learning"),
    "DECODER": ("Decoder", "Sub-network generating output sequences autoregressively from latent context vectors.", "Deep Learning"),
    "DATASET": ("Dataset", "Structured collection of sample instances used for training, validation, and testing.", "Machine Learning"),
    "ENTROPY": ("Entropy", "Information-theoretic measure of unpredictability and uncertainty in a probability distribution.", "Information Theory"),
    "PRUNING": ("Pruning", "Technique removing redundant weights or neurons to reduce model memory footprint.", "Deep Learning"),
    
    # 8-letter
    "GRADIENT": ("Gradient", "Vector of partial derivatives pointing in the direction of steepest ascent of a loss function.", "Mathematics"),
    "ACCURACY": ("Accuracy", "Proportion of correct predictions among the total number of evaluated cases.", "Evaluation"),
    "VARIANCE": ("Variance", "Sensitivity of model predictions to fluctuations and random noise in the training set.", "Machine Learning"),
    "BOOSTING": ("Boosting", "Ensemble technique training weak learners sequentially, with each correcting predecessors.", "Machine Learning"),
    
    # 9-letter
    "ATTENTION": ("Attention", "Dynamic Query-Key-Value mechanism calculating pairwise relevance weights across tokens.", "Generative AI"),
    "INFERENCE": ("Inference", "Evaluating a trained model on new inputs to generate predictions without weight updates.", "Machine Learning"),
    "EMBEDDING": ("Embedding", "Dense continuous vector mapping discrete symbols into semantic geometric space.", "NLP / Deep Learning"),
    "PRECISION": ("Precision", "Ratio of correctly predicted positive observations to total predicted positive observations.", "Evaluation"),
    "OPTIMIZER": ("Optimizer", "Algorithm adjusting neural network weights based on loss gradients (e.g. Adam, SGD).", "Optimization"),
    
    # 10-letter
    "PERCEPTRON": ("Perceptron", "Fundamental linear threshold artificial neuron introduced by Frank Rosenblatt.", "Deep Learning"),
    "CLUSTERING": ("Clustering", "Unsupervised method grouping unlabeled data points by spatial distance metrics.", "Machine Learning"),
    "REGRESSION": ("Regression", "Supervised task predicting continuous real-valued quantitative targets.", "Machine Learning"),
    "PREDICTION": ("Prediction", "Estimated output or label generated by a trained model given novel input features.", "Machine Learning"),
    
    # 11-letter
    "TRANSFORMER": ("Transformer", "Neural architecture based entirely on self-attention mechanisms without recurrence.", "Generative AI"),
    "CONVOLUTION": ("Convolution", "Mathematical filtering operation computing dot products with sliding learnable kernels.", "Computer Vision"),
    "OVERFITTING": ("Overfitting", "Pathology where a model memorizes training noise at the expense of generalization.", "Machine Learning"),
    "AUTOENCODER": ("Autoencoder", "Unsupervised network trained to compress and reconstruct its own input data.", "Deep Learning"),
    "TOKENIZATION": ("Tokenization", "Process of converting raw natural language text into discrete token identifiers.", "Generative AI"),
    "EIGENVECTOR": ("Eigenvector", "Vector whose direction is invariant under a given linear matrix transformation.", "Mathematics"),
    
    # 12-letter
    "OPTIMIZATION": ("Optimization", "Mathematical process of finding parameter values that minimize or maximize an objective function.", "Mathematics"),
    
    # 13-letter
    "NORMALIZATION": ("Normalization", "Layer or batch technique standardizing activation distributions to stabilize learning.", "Deep Learning"),
    "HALLUCINATION": ("Hallucination", "Unfaithful, ungrounded, or fabricated output generated by large language models.", "Generative AI"),
    
    # 14-letter
    "REGULARIZATION": ("Regularization", "Technique introducing loss penalties (L1/L2) to prevent overfitting.", "Machine Learning"),
    "CLASSIFICATION": ("Classification", "Supervised task of categorizing input instances into discrete classes.", "Machine Learning"),
    
    # 15-letter
    "BACKPROPAGATION": ("Backpropagation", "Algorithm calculating gradients backward through computational graphs via chain rule.", "Deep Learning"),
    "GRADIENTDESCENT": ("Gradient Descent", "Iterative first-order optimization algorithm stepping opposite the loss gradient.", "Optimization")
}

def search_valid_puzzle():
    # Let's create candidate layouts and verify them
    # We will build 3 beautiful puzzles by constructing intersecting words systematically
    
    # --- PUZZLE 1: AI & ML Flagship Championship (15x15) ---
    # Let's assemble verified words:
    p1_words = [
        # Across
        {"id": "p1_a1", "word": "BACKPROPAGATION", "direction": "across", "row": 0, "col": 0},
        # Col 0: B, Col 4: P, Col 8: A, Col 10: A, Col 12: I, Col 14: N
        
        # Down from row 0
        {"id": "p1_d1", "word": "BIAS",            "direction": "down", "row": 0, "col": 0},   # (0,0)=B, (1,0)=I, (2,0)=A, (3,0)=S
        {"id": "p1_d2", "word": "PERCEPTRON",      "direction": "down", "row": 0, "col": 4},   # (0,4)=P, (1,4)=E, (2,4)=R, (3,4)=C, (4,4)=E, (5,4)=P, (6,4)=T, (7,4)=R, (8,4)=O, (9,4)=N
        {"id": "p1_d3", "word": "AUTOENCODER",     "direction": "down", "row": 0, "col": 8},   # (0,8)=A, (1,8)=U, (2,8)=T, (3,8)=O, (4,8)=E, (5,8)=N, (6,8)=C, (7,8)=O, (8,8)=D, (9,8)=E, (10,8)=R
        {"id": "p1_d4", "word": "ATTENTION",       "direction": "down", "row": 0, "col": 10},  # (0,10)=A, (1,10)=T, (2,10)=T, (3,10)=E, (4,10)=N, (5,10)=T, (6,10)=I, (7,10)=O, (8,10)=N
        {"id": "p1_d5", "word": "NORMALIZATION",   "direction": "down", "row": 0, "col": 14},  # (0,14)=N, (1,14)=O, (2,14)=R, (3,14)=M, (4,14)=A, (5,14)=L, (6,14)=I, (7,14)=Z, (8,14)=A, (9,14)=T, (10,14)=I, (11,14)=O, (12,14)=N
        
        # Across row 2:
        # At (2,0): A (from BIAS), at (2,4): R (from PERCEPTRON), at (2,8): T (from AUTOENCODER), at (2,10): T (from ATTENTION), at (2,14): R (from NORMALIZATION)
        # Let's check: (2,7) to (2,10) is T...T? At (2,8)=T, (2,10)=T.
        # Word at (2,6) len 5: _ _ T _ T ? Let's check: L A T E N T at (2,6)? (2,6)=L, (2,7)=A, (2,8)=T, (2,9)=E, (2,10)=N? But ATTENTION[2]=T.
        # What if (2,0)=A, (2,1)=C, (2,2)=C, (2,3)=U, (2,4)=R, (2,5)=A, (2,6)=C, (2,7)=Y ?
        # ACCURACY (len 8, row 2, col 0):
        # (2,0)=A (BIAS[2]=A!), (2,1)=C, (2,2)=C, (2,3)=U, (2,4)=R (PERCEPTRON[2]=R!), (2,5)=A, (2,6)=C, (2,7)=Y! PERFECT MATCH!
        {"id": "p1_a2", "word": "ACCURACY",        "direction": "across", "row": 2, "col": 0},
        
        # Across row 3:
        # At (3,0)=S (from BIAS), (3,4)=C (from PERCEPTRON), (3,8)=O (from AUTOENCODER), (3,10)=E (from ATTENTION), (3,14)=M (from NORMALIZATION)
        # Word at (3,0) len 4: S G D ? (len 3) -> S G D at (3,0)? (3,0)=S, (3,1)=G, (3,2)=D.
        {"id": "p1_a3", "word": "SGD",             "direction": "across", "row": 3, "col": 0},
        
        # Across row 4:
        # At (4,4)=E (from PERCEPTRON), (4,8)=E (from AUTOENCODER), (4,10)=N (from ATTENTION), (4,14)=A (from NORMALIZATION)
        # Word at (4,7) len 4: _ E _ N ? R E I N ?
        # Word at (4,2) to (4,6) len 5: _ _ E _ _ ?
        # Let's check: L A Y E R at (4,2): (4,2)=L, (4,3)=A, (4,4)=Y? But PERCEPTRON[4]=E.
        # What about R E L U at (4,4)? (4,4)=R? No, PERCEPTRON[4]=E.
        # What about T E N S O R at (4,3)? (4,3)=T, (4,4)=E (PERCEPTRON[4]=E!), (4,5)=N, (4,6)=S, (4,7)=O, (4,8)=R? But AUTOENCODER[4]=E.
        # What about R E S N E T at (4,4)? (4,4)=R? No.
        
        # Let's let the computer find exact placements across all rows!
    ]
    return p1_words

if __name__ == "__main__":
    pass
